
mask:
  use_dynamic_thre: 0
  difference_map_threshold_left: -0.1
  difference_map_threshold_right: 0.28
  difference_map_threshold: 0.6

  error_views: [""]

  area_threshold: 50
  render_to_bin: 60
  grid_size: [18]
  IoU_threshold: 0.2

  prune: 0
  detect_overlap: 0

evaluation:
  mask_threshold: 1